### ISSUE TITLE
FileRead.java should be updated

### ISSUE THREAD

**Issue by YesseniaValencia** [UCSB-CS56-Projects/cs56-languages-vocab-quiz#12] opened 2016-02-29 12:22 UTC
It keeps bringing up that FileRead.java is using a deprecated API. On Oracle, the method used to read files by characters or data have been updated to using different classes, such as FileReader and BufferedReader instead of DataInputStream and the like. It should be reimplemented using the more updated classes.

**Comment by arda-** [comment] 2016-03-11 02:23
approved; 150 pts

**Comment by YesseniaValencia** [comment] 2016-03-11 09:39
I added some of the issues I had worked on. I will add the rest by tomorrow including the updated README.md (I’m a little confused there, do I add to it, rewrite it?). Will also add new .md file with the issues for the next generation.

**Comment by jmangel** [comment] 2016-10-06 18:32
Unable to reproduce; @arda-, @YesseniaValencia is this still open?

**Comment by arda-** [comment] 2016-10-06 18:34
if you can't works

**Comment by arda-** [comment] 2016-10-06 18:35
whoops, thanks autocorrect. 

** If you can't reproduce, and you have enough other issues in the repo, feel free to close it.

**Closed** 2016-10-13 05:17 UTC
